version: 1.0.{build}
image: Visual Studio 2015
install:
- ps: |
    Install-PackageProvider -Name NuGet –Force
    Install-Package -Name Pester -ProviderName PowerShellGet -Scope AllUsers -Force
    Install-Module -Name PSScriptAnalyzer -Scope AllUsers –Force
    Import-Module -Name Pester
    Import-Module -Name PSScriptAnalyzer
build: off
after_test:
- ps: |
    7z a -tzip "${Env:APPVEYOR_BUILD_FOLDER}\${Env:APPVEYOR_PROJECT_NAME}.zip" "${Env:APPVEYOR_BUILD_FOLDER}\*"
    7z a -tzip "${Env:APPVEYOR_BUILD_FOLDER}\${Env:APPVEYOR_PROJECT_NAME}.zip" "${Env:APPVEYOR_BUILD_FOLDER}\Tests\deploy.ps1"
test_script:
- ps: |
    $testResultsFile = ".\TestsResults.xml"
    $results = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($Env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
    If ($results.FailedCount -gt 0) {
      Throw "$($results.FailedCount) tests failed."
    }
artifacts:
- path: '*.zip'
  name: PSAppDeployToolkit
deploy:
- provider: Environment
  name: FileServer
notifications:
- provider: Webhook
  url: https://msudenver.webhook.office.com/webhookb2/dc44621d-45b2-4321-840e-150c8de1fd96@03309ca4-1733-4af9-a73c-f18cc841325c/IncomingWebhook/aba499ffe4694db680453d69e9164a00/2caf0698-fcd6-4523-999c-1a26d166db78
  method: POST
  content_type: application/json
  body: >-
    {
        "title": "AppVeyor Build {{#passed}}passed{{/passed}}{{#failed}}failed{{/failed}}",
        "summary": "Build {{projectName}} {{buildVersion}} {{status}}",
        "themeColor": "{{#passed}}00FF00{{/passed}}{{#failed}}FF0000{{/failed}}",
        "sections": [
            {
                "activityTitle": "{{commitAuthor}} on {{commitDate}} ( {{repositoryProvider}}/{{repositoryName}} )",
                "activityText": "[Build {{projectName}} {{buildVersion}} {{status}}]({{buildUrl}})"
            },
            {
                "title": "Details",
                "facts": [
                    {
                        "name": "Commit",
                        "value": "[{{commitId}} by {{commitAuthor}} on {{branch}} at {{commitDate}}]({{commitUrl}})"
                    },
                    {
                        "name": "Message",
                        "value": "{{commitMessage}}"
                    },
                    {
                        "name": "Duration",
                        "value": "{{duration}} ({{started}} - {{finished}})"
                    }
                ]
            }
        ]
    }
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true